# Generated by Django 5.1.5 on 2025-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=10, unique=True)),
                ('nome_entregador', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
